/**
 * Generates supabase/seed.sql from shared code so the seeded protocol JSON and bounty H3 cells can
 * never drift from packages/shared. Run: pnpm --filter @groundtruth/supabase seed:gen
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { cellsForCircle, circlePolygon, DEMO, streetFloodDepth } from "@groundtruth/shared";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const cells = cellsForCircle(DEMO.lat, DEMO.lng, DEMO.radiusM);
const area = circlePolygon(DEMO.lat, DEMO.lng, DEMO.radiusM);

const sql = `-- GENERATED by supabase/scripts/generate-seed.ts. Do not edit by hand.
-- Researcher/admin login: ${DEMO.researcherEmail} / ${DEMO.researcherPassword}

-- researcher / admin account (email + password)
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values (
  '00000000-0000-0000-0000-000000000000', ${q(DEMO.researcherId)}, 'authenticated', 'authenticated',
  ${q(DEMO.researcherEmail)}, extensions.crypt(${q(DEMO.researcherPassword)}, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Demo Researcher"}'::jsonb, now(), now(),
  '', '', '', ''
) on conflict (id) do nothing;

insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (
  gen_random_uuid(), ${q(DEMO.researcherId)}, ${q(DEMO.researcherId)},
  jsonb_build_object('sub', ${q(DEMO.researcherId)}, 'email', ${q(DEMO.researcherEmail)}, 'email_verified', true),
  'email', now(), now(), now()
) on conflict do nothing;

-- the auth trigger created the profile as a contributor; promote it
update public.profiles
   set role = 'admin', display_name = 'Demo Researcher', is_adult = true, consent_license = true
 where id = ${q(DEMO.researcherId)};

-- flood protocol (published)
insert into public.protocols (id, slug, version, name, definition, status, created_by)
values (
  ${q(DEMO.protocolId)}, ${q(streetFloodDepth.slug)}, ${streetFloodDepth.version}, ${q(streetFloodDepth.name)},
  ${json(streetFloodDepth)}, 'published', ${q(DEMO.researcherId)}
) on conflict (id) do update set definition = excluded.definition, status = 'published';

-- one active demo bounty
insert into public.bounties (
  id, protocol_id, created_by, title, summary, area, center_lat, center_lng, radius_m, h3_res, cells,
  starts_at, ends_at, event_started_at, base_price_cents, max_price_cents, target_per_cell, priority,
  budget_cents, spent_cents, status, source
) values (
  ${q(DEMO.bountyId)}, ${q(DEMO.protocolId)}, ${q(DEMO.researcherId)},
  ${q(DEMO.title)}, ${q(DEMO.summary)}, ${json(area)}, ${DEMO.lat}, ${DEMO.lng}, ${DEMO.radiusM}, 9,
  array[${cells.map(q).join(", ")}]::text[],
  now() - interval '1 hour', now() + interval '7 days', now() - interval '20 minutes',
  ${DEMO.baseCents}, ${DEMO.maxCents}, ${DEMO.targetPerCell}, 1, ${DEMO.budgetCents}, 0, 'active', 'demo'
) on conflict (id) do nothing;
`;

const out = fileURLToPath(new URL("../seed.sql", import.meta.url));
writeFileSync(out, sql);
console.log(`wrote ${out} (${cells.length} cells)`);
