/**
 * Generates supabase/seed.sql from shared code so the seeded protocol JSON and bounty H3 cells can
 * never drift from packages/shared. Run: pnpm --filter @groundtruth/supabase seed:gen
 *
 * Admin password: never committed. The seed carries only a bcrypt hash (computed here with PGlite's
 * pgcrypto, the same crypt() Supabase Auth verifies) of SEED_ADMIN_PASSWORD, or of a random password
 * that is printed ONCE to this terminal. seed.sql inserts the admin with "on conflict do nothing", so
 * an existing hosted admin keeps its password: rotate that with apps/web/scripts/rotate-admin-password.ts.
 */
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";
import { cellsForCircle, circlePolygon, DEMO, streetFloodDepth } from "@groundtruth/shared";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const fromEnv = process.env.SEED_ADMIN_PASSWORD?.trim();
if (fromEnv !== undefined && fromEnv.length > 0 && fromEnv.length < 12) throw new Error("SEED_ADMIN_PASSWORD must be at least 12 characters");
const adminPassword = fromEnv || randomBytes(18).toString("base64url");
const pg = new PGlite({ extensions: { pgcrypto } });
await pg.exec("create extension if not exists pgcrypto");
const hashRow = await pg.query<{ h: string }>("select crypt($1, gen_salt('bf', 10)) as h", [adminPassword]);
await pg.close();
const adminHash = hashRow.rows[0]?.h;
if (!adminHash?.startsWith("$2")) throw new Error("bcrypt hashing failed");

const cells = cellsForCircle(DEMO.lat, DEMO.lng, DEMO.radiusM);
const area = circlePolygon(DEMO.lat, DEMO.lng, DEMO.radiusM);

const sql = `-- GENERATED by supabase/scripts/generate-seed.ts. Do not edit by hand.
-- Researcher/admin login: ${DEMO.researcherEmail}. The password is not in this file (bcrypt hash only).

-- researcher / admin account (email + password)
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
) values (
  '00000000-0000-0000-0000-000000000000', ${q(DEMO.researcherId)}, 'authenticated', 'authenticated',
  ${q(DEMO.researcherEmail)}, ${q(adminHash)}, now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Demo Researcher"}'::jsonb, now(), now(),
  '', '', '', ''
) on conflict (id) do nothing;

insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (
  gen_random_uuid(), ${q(DEMO.researcherId)}, ${q(DEMO.researcherId)},
  jsonb_build_object('sub', ${q(DEMO.researcherId)}, 'email', ${q(DEMO.researcherEmail)}, 'email_verified', true),
  'email', now(), now(), now()
) on conflict do nothing;

-- the auth trigger created the profile as a contributor; promote it
update public.profiles
   set role = 'admin', is_admin = true, is_researcher = true, display_name = 'Demo Researcher', is_adult = true, consent_license = true
 where id = ${q(DEMO.researcherId)};

-- flood protocol (published)
insert into public.protocols (id, slug, version, name, definition, status, created_by)
values (
  ${q(DEMO.protocolId)}, ${q(streetFloodDepth.slug)}, ${streetFloodDepth.version}, ${q(streetFloodDepth.name)},
  ${json(streetFloodDepth)}, 'published', ${q(DEMO.researcherId)}
) on conflict (id) do update set definition = excluded.definition, status = 'published';

-- one active demo bounty
insert into public.bounties (
  id, protocol_id, created_by, title, summary, area, center_lat, center_lng, radius_m, h3_res, cells,
  starts_at, ends_at, event_started_at, base_price_cents, max_price_cents, target_per_cell, priority,
  budget_cents, spent_cents, status, source, sponsor_name, sponsor_url
) values (
  ${q(DEMO.bountyId)}, ${q(DEMO.protocolId)}, ${q(DEMO.researcherId)},
  ${q(DEMO.title)}, ${q(DEMO.summary)}, ${json(area)}, ${DEMO.lat}, ${DEMO.lng}, ${DEMO.radiusM}, 9,
  array[${cells.map(q).join(", ")}]::text[],
  now() - interval '1 hour', now() + interval '7 days', now() - interval '20 minutes',
  ${DEMO.baseCents}, ${DEMO.maxCents}, ${DEMO.targetPerCell}, 1, ${DEMO.budgetCents}, 0, 'active', 'demo',
  ${q(DEMO.sponsorName)}, ${DEMO.sponsorUrl === null ? "null" : q(DEMO.sponsorUrl)}
) on conflict (id) do update
  -- an existing demo bounty (e.g. the hosted DB) only gains a sponsor; nothing else is touched
  set sponsor_name = coalesce(public.bounties.sponsor_name, excluded.sponsor_name),
      sponsor_url = coalesce(public.bounties.sponsor_url, excluded.sponsor_url);

-- sponsor pool (migration 000007): the demo budget is recorded as an earmarked sponsor contribution
-- + allocation, so pool totals match bounty budgets. Idempotent.
select public.pool_backfill_legacy();
`;

const out = fileURLToPath(new URL("../seed.sql", import.meta.url));
writeFileSync(out, sql);
console.log(`wrote ${out} (${cells.length} cells)`);
if (fromEnv) console.log(`admin ${DEMO.researcherEmail}: password from SEED_ADMIN_PASSWORD`);
else console.log(`admin ${DEMO.researcherEmail} password (shown once, store it now): ${adminPassword}`);
